//Hi Hello , Welcome you thank you for asking and I am very Happy

//Starting the Project
const starthttp = require("http");
const save_file = require("fs")

//Handling the Client
function handle(req,res){
    console.log("Please Wait...")
    console.log("The Url : "+req.url)
    console.log("Method : "+req.method)
    res.setHeader("content-type","text/html")
    res.write(" <!DOCTYPE html> ")
    res.write(" <html lang='en'> ")
    res.write(" <head> ")
    res.write("     <meta charset='UTF-8'> ")
    res.write("     <meta name='viewport' content='width=device-width, initial-scale=1.0'> ")
    res.write("     <title>Comments</title> ")
    res.write("     <style> ")
    res.write("         *{ ")
    res.write("             padding: 0; ")
    res.write("             margin: 0; ")
    res.write("             box-sizing: border-box; ")
    res.write("         } ")
    res.write("         body{ ")
    res.write("             width: 100vw; ")
    res.write("             height: 100vh; ")
    res.write("             background-color: #000; ")
    res.write("             color: white; ")
    res.write("             display: flex; ")
    res.write("             justify-content: center; ")
    res.write("             align-items: center; ")
    res.write("         } ")
    res.write("         .form{ ")
    res.write("             display: flex; ")
    res.write("             flex-direction: column; ")
    res.write("         } ")
    res.write("         label{ ")
    res.write("             margin-bottom: 15px; ")
    res.write("         } ")
    res.write("         .btn{ ")
    res.write("             margin-top: 15px; ")
    res.write("         } ")
    res.write("         textarea{ ")
    res.write("             border: 1px solid #555; ")
    res.write("             background-color: #000; ")
    res.write("             padding: 10px; ")
    res.write("             border-radius: 10px; ")
    res.write("             color: #555; ")
    res.write("         } ")
    res.write("         button{ ")
    res.write("             background-color: #555; ")
    res.write("             height: 30px; ")
    res.write("             border: 1px solid #555; ")
    res.write("             border-radius: 10px; ")
    res.write("             color: white; ")
    res.write("         } ")
    res.write("         button:hover{ ")
    res.write("             background-color: #555; ")
    res.write("             border-color: wheat; ")
    res.write("         } ")
    res.write("         button:active{ ")
    res.write("             color: wheat; ")
    res.write("         } ")
    res.write("  ")
    res.write("     </style> ")
    res.write(" </head> ")
    res.write(" <body> ")
    res.write("     <div class='container'> ")
    res.write("        <form class='form' action='/send' method = 'POST'> ")
    res.write("         <label for='comment'>Enter Your Feedback :</label> ")
    res.write("         <textarea placeholder='Text here  !' class='form-control' name='comment' id='comment' cols='30' rows='10'></textarea> ")
    res.write("         <button  class='btn btn-success'>Submit</button> ")
    res.write("        </form> ")
    res.write("     </div> ")
    res.write(" </body> ")
    res.write(" </html> ")

if (req.url === "/send"  && req.method == "POST")
    console.log("Post is Received")
    let body = [];
    req.on("data",(chuck)=>{
        console.log("Message is Buffered")
        console.log(chuck)
        body.push(chuck)
        const parsedbody = Buffer.concat(body).toString();
        let message = parsedbody.split("=")
        message = message[1].split("+")
        let store="";
        for (data of message){
            store = store+" "+data;
        }
        console.log(store)
        save_file.writeFileSync("Comments.txt",store)
    })
}

const client = starthttp.createServer(handle)

client.listen(3000)